# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'QPayiPhone' do

pod 'Venmo-iOS-SDK', '~>1.3'

pod 'Parse', '~> 1.3'

end

target 'QPayiPhoneTests' do

end

